Erstellen einer numpy-Reihung von Gleitkommazahlen mit Zahlen von 0 bis 4.

In [23]:
import numpy as np

float_series = np.arange(0, 4 + 1, 0.1)
print(float_series)


[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9]


Erzeugen folgender numpy-Matrix: `M = [[1,2,3][4,5,6]]`.

In [6]:
matrix = np.array([[1, 2, 3],[4, 5, 6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


Abfragen der Dimension einer Matrix.

In [8]:
dimension: int = matrix.shape
print(dimension)

(2, 3)


Überprüfen, ob Wert 2 in Matrix enthalten.

In [21]:
# Format = Zeile, Spalte
matrixContainsTwo: bool = (2 in matrix[:, :])
print(matrixContainsTwo)

True


Reihung gegeben: `a = np.array([0,1,2,3,4,5,6,7,8,9], float)`. Ändern Sie die Dimension in eine 5x2 Matrix ab.

In [25]:
a = np.array([0,1,2,3,4,5,6,7,8,9], float)
print("Von")
print(a)

a.shape = (5, 2)
print("Zu")
print(a)

Von
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
Zu
[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]


Transponieren der Matrix M.

In [26]:
a_transp = a.transpose()
print(a_transp)

[[0. 2. 4. 6. 8.]
 [1. 3. 5. 7. 9.]]


Abwandeln der Matrix in Reihung

In [28]:
a_reihung = a.flatten()
print(a_reihung)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


Gegeben ist Reihung `b = np.array([0,1,2,3], float)`. Erhöhen Sie Dimension der Reihung.

In [41]:
b = np.array([0,1,2,3], float)
print("Von")
print(b)

new_b = np.expand_dims(b, axis=1)
print("Zu")
print(new_b)


Von
[0. 1. 2. 3.]
Zu
[[0.]
 [1.]
 [2.]
 [3.]]


3x3-Identitätsmatrix generieren.

In [43]:
m_i = np.identity(3)
print(m_i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
