Gegeben seien die folgenden zwei Reihungen `a = np.array([1,2,3], float)` und `b = np.array([4,5,6], float)`, berechnen sie das Skalarprodukt von `a` und `b`.

In [8]:
import numpy as np

a = np.array([1,2,3], float)
b = np.array([4,5,6], float)

scalar_a = np.linalg.norm(a)
scalar_b = np.linalg.norm(b)

print(f"norm(a): {scalar_a}")
print(f"norm(b): {scalar_b}")
print(f"norm(a) + norm(b): {scalar_a + scalar_b}")

norm(a): 3.7416573867739413
norm(b): 8.774964387392123
norm(a) + norm(b): 12.516621774166063


Gegeben sei die Matrix `M = [[1,2,3], [4,5,6], [7,8,9]]`, berechnen sie die Determinante der Matrix indem sie das `linalg`-Paket der Numpy-Bibliothek verwenden.

In [11]:
M = [[1,2,3], [4,5,6], [7,8,9]]

det: int = np.linalg.det(M)
print(det)

0.0


Berechnen sie auch die Eigenwerte und -vektoren der Matrix `M`.

In [12]:
eigenwerte = np.linalg.eigh(M)
print(eigenwerte)

(array([-3.15746784, -0.67276795, 18.8302358 ]), array([[-0.80238891,  0.43402538, -0.40962667],
       [-0.16812656, -0.82296167, -0.54264865],
       [ 0.57263033,  0.36654613, -0.73330651]]))


Berechnen sie die Inverse der Matrix.

In [19]:
b = np.array([[1,1,2], [3,-6,7], [0,3,5]])
print("Von")
print(b)

inverseMatrix = np.linalg.inv(b)
print("Zu")
print(inverseMatrix)

Von
[[ 1  1  2]
 [ 3 -6  7]
 [ 0  3  5]]
Zu
[[ 1.0625     -0.02083333 -0.39583333]
 [ 0.3125     -0.10416667  0.02083333]
 [-0.1875      0.0625      0.1875    ]]


Gegeben sei die Reihung `c = np.array([1,4,3,8,3,2,3], float)`, berechnen sie den Mittelwert der Reihungselemente.

In [28]:
c = np.array([1,4,3,8,3,2,3], float)
mittel: int = np.mean(c)
print(mittel)
# print(24 / 7)

3.4285714285714284


Berechnen sie den Median der Reihungselemente

In [27]:
median: int = np.median(c)
print(median)

3.0
